Various QOL fixes (#234)
* add lint rake task and address issues
* update ruby version
* update makefile to use rake target
* ignore site (should never be commited tho)
* Update last updated fields
* improve last updated at script
* add rake lint
* add CI check for missing last updates

diff --git a/.github/workflows/accessibility.yml b/.github/workflows/accessibility.yml
--- a/.github/workflows/accessibility.yml
+++ b/.github/workflows/accessibility.yml
@@ -10,6 +10,8 @@ jobs:
     steps:
       - name: Checkout source.
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          fetch-depth: 0
 
       - run: corepack enable
       - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
@@ -27,6 +29,15 @@ jobs:
       - name: Install pa11y-ci dependencies.
         run: yarn install
 
+      - name: Check last updated dates.
+        run: |
+          cd docs
+          bundle exec rake update_last_updated
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error::last updated not updated"
+            exit 1
+          fi
+
       - name: markdown lint
         uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
         with:
@@ -35,6 +46,7 @@ jobs:
             !docs/assets/**
             !docs/_sass/**
             !docs/vendor/**
+            !docs/_site/**
 
       - name: Start up jekyll server.
         run: yarn start-detached
