add CI check for missing last updates

diff --git a/.github/workflows/accessibility.yml b/.github/workflows/accessibility.yml
--- a/.github/workflows/accessibility.yml
+++ b/.github/workflows/accessibility.yml
@@ -27,6 +27,15 @@ jobs:
       - name: Install pa11y-ci dependencies.
         run: yarn install
 
+      - name: Check last updated dates.
+        run: |
+          cd docs
+          bundle exec rake update_last_updated
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error::last updated not updated"
+            exit 1
+          fi
+
       - name: markdown lint
         uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
         with:
